divert(-1)
define(TITLE, %[Tales of My life]%)
define(AUTHOR, %[Fahd Ouassarni]%)
define(PROFILE, %[https://avatars2.githubusercontent.com/u/24702495?s=460&v=4]%)
define(ALT_PROFILE, %[Profile picture]%)
define(RESUME_LINK, %[https://raw.githubusercontent.com/ouassarnifahd/latex-cv-resume/embedded-software-developer/output/fahd-ouassarni-embedded-software-developer-en.pdf]%)
define(CV_LINK, %[https://raw.githubusercontent.com/ouassarnifahd/latex-cv-resume/embedded-software-developer/output/fahd-ouassarni-embedded-software-developer-fr.pdf]%)
